

var error = {
    COUNTRY_GET_ERROR:          "COUNTRY_GET_ERROR",
    CITY_GET_ERROR:             "CITY_GET_ERROR",

    USER_NOT_FOUND:             "USER_NOT_FOUND",
    IDENTIFICATOR_IS_ABSENT:    "IDENTIFICATOR_IS_ABSENT",
    IDENTIFICATOR_IS_BUSY:      "IDENTIFICATOR_IS_BUSY",

    PASSWORD_IS_ABSENT:         "PASSWORD_IS_ABSENT",
    PASSWORD_IS_INCORRECT:      "PASSWORD_IS_INCORRECT",

    OAUTH_INCORRECT:                  "OAUTH_INCORRECT",

    VK_USER_ACCESSTOKEN_IS_INCORRECT:   "VK_USER_ACCESSTOKEN_IS_INCORRECT",
    VK_APP_ACCESSTOKEN_NOT_GOT:         "VK_APP_ACCESSTOKEN_NOT_GOT",
    VK_INCORRECT_ACCESS_TOKEN:          "VK_INCORRECT_ACCESS_TOKEN",
    VK_USER_NOT_REGISTRED:              "VK_USER_NOT_REGISTRED",

    FACEBOOK_USER_ACCESSTOKEN_IS_INCORRECT: "FACEBOOK_USER_ACCESSTOKEN_IS_INCORRECT",
    FACEBOOK_USER_NOT_REGISTRED: "FACEBOOK_USER_NOT_REGISTRED",

    GOOGLE_USER_ACCESSTOKEN_IS_INCORRECT: "GOOGLE_USER_ACCESSTOKEN_IS_INCORRECT",
    GOOGLE_USER_NOT_REGISTRED: "GOOGLE_USER_NOT_REGISTRED",


    ACTIVITY_INCORRECT: "ACTIVITY_INCORRECT",
    ACTIVITY_NOT_FOUND: "ACTIVITY_NOT_FOUND",

    COMMENT_INCORRECT_IDENTIFICATOR: "COMMENT_INCORRECT_IDENTIFICATOR",
    COMMENT_TEXT_ABSENT: "COMMENT_TEXT_ABSENT",
    COMMENTS_ABSENT: "COMMENTS_ABSENT",

    VALUE_INCORRECT_BODY: "VALUE_INCORRECT_BODY",
    VALUE_CHANGING_FAILED: "VALUE_CHANGING_FAILED",
    VALUE_REMOVING_FAILDED: "VALUE_REMOVING_FAILDED"

};

module.exports = error;