

var error = {

    USER_NOT_FOUND:             "USER_NOT_FOUND",
    IDENTIFICATOR_IS_ABSENT:    "IDENTIFICATOR_IS_ABSENT",
    IDENTIFICATOR_IS_BUSY:      "IDENTIFICATOR_IS_BUSY",
    PASSWORD_IS_ABSENT:         "PASSWORD_IS_ABSENT",
    PASSWORD_IS_INCORRECT:      "PASSWORD_IS_INCORRECT"

};

module.exports = error;