
var log = {

    db: {
        CONNECTION_SUCCESS: 'CONNETCTION WITH DATABASE HAS BEEN %s ESTABLISHED SUCCESSFULLY',
        CONNECTION_FAILURE: 'CONNECTION TO THE DATABASE IS NOT ESTABLISHED:'
    }
};

module.exports = log;
